# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: helloworld/helloworld.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

#import helloworld.helloworld_pb2
import facial_emotions_pb2


class Emotion_recognizerBase(abc.ABC):

    @abc.abstractmethod
    async def image_processor(self, stream):
        pass

    @abc.abstractmethod
    async def emotion_classifier(self, stream):
        pass

    @abc.abstractmethod
    async def StreamStreamEmotion(self, stream):
        pass

    def __mapping__(self):
        return {
            '/facial_emotions.Emotion_recognizer/image_processor': grpclib.const.Handler(
                self.image_processor,
                grpclib.const.Cardinality.STREAM_STREAM,
                facial_emotions_pb2.image_frame,
                facial_emotions_pb2.Rects,
            ),
            '/facial_emotions.Emotion_recognizer/emotion_classifier': grpclib.const.Handler(
                self.emotion_classifier,
                grpclib.const.Cardinality.STREAM_STREAM,
                facial_emotions_pb2.face_emotion,
                facial_emotions_pb2.Emotion,
            ),
            '/facial_emotions.Emotion_recognizer/StreamStreamEmotion': grpclib.const.Handler(
                self.StreamStreamEmotion,
                grpclib.const.Cardinality.STREAM_STREAM,
                facial_emotions_pb2.emoRequest,
                facial_emotions_pb2.emoReply,
            ),
        }


class Emotion_recognizerStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        '''self.FaceNum = grpclib.client.StreamStreamMethod1(
            channel,
            '/facial_emotions.Emotion_recognizer/FaceNum',
            facial_emotions_pb2.face_num_request,
            facial_emotions_pb2.face_num_reply,
        )'''
        self.image_processor = grpclib.client.StreamStreamMethod(
            channel,
            '/facial_emotions.Emotion_recognizer/image_processor',
            facial_emotions_pb2.image_frame,
            facial_emotions_pb2.Rects,
        )
        self.emotion_classifier = grpclib.client.StreamStreamMethod(
            channel,
            '/facial_emotions.Emotion_recognizer/emotion_classifier',
            facial_emotions_pb2.face_emotion,
            facial_emotions_pb2.Emotion,
        )
        self.StreamStreamEmotion = grpclib.client.StreamStreamMethod(
            channel,
            '/facial_emotions.Emotion_recognizer/StreamStreamEmotion',
            facial_emotions_pb2.emoRequest,
            facial_emotions_pb2.emoReply,
        )
