# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facial_emotions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='facial_emotions.proto',
  package='facial_emotions',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x66\x61\x63ial_emotions.proto\x12\x0f\x66\x61\x63ial_emotions\"!\n\x0bimage_frame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"-\n\x05Rects\x12$\n\x05rects\x18\x01 \x03(\x0b\x32\x15.facial_emotions.Rect\"2\n\x04Rect\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x14\n\x03ret\x12\r\n\x05reply\x18\x01 \x01(\t\"G\n\x0c\x66\x61\x63\x65_emotion\x12\x37\n\x0e\x65motion_labels\x18\x01 \x03(\x0b\x32\x1f.facial_emotions.Emotion_labels\"\x1a\n\x07\x45motion\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\"}\n\x0e\x45motion_labels\x12\r\n\x05\x61ngry\x18\x01 \x01(\t\x12\x0f\n\x07\x64isgust\x18\x02 \x01(\t\x12\x0c\n\x04\x66\x65\x61r\x18\x03 \x01(\t\x12\r\n\x05happy\x18\x04 \x01(\t\x12\x0b\n\x03sad\x18\x05 \x01(\t\x12\x10\n\x08surprise\x18\x06 \x01(\t\x12\x0f\n\x07neutral\x18\x07 \x01(\t\"\x1e\n\nemoRequest\x12\x10\n\x08\x65molabel\x18\x01 \x01(\t\"4\n\x08\x65moReply\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\x12\x17\n\x0fnumber_of_faces\x18\x02 \x01(\x05\x32\x8d\x02\n\x12\x45motion_recognizer\x12M\n\x0fimage_processor\x12\x1c.facial_emotions.image_frame\x1a\x16.facial_emotions.Rects\"\x00(\x01\x30\x01\x12S\n\x12\x65motion_classifier\x12\x1d.facial_emotions.face_emotion\x1a\x18.facial_emotions.Emotion\"\x00(\x01\x30\x01\x12S\n\x13StreamStreamEmotion\x12\x1b.facial_emotions.emoRequest\x1a\x19.facial_emotions.emoReply\"\x00(\x01\x30\x01\x62\x06proto3')
)




_IMAGE_FRAME = _descriptor.Descriptor(
  name='image_frame',
  full_name='facial_emotions.image_frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='facial_emotions.image_frame.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=75,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='facial_emotions.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='facial_emotions.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='facial_emotions.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=106,
)


_RECTS = _descriptor.Descriptor(
  name='Rects',
  full_name='facial_emotions.Rects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rects', full_name='facial_emotions.Rects.rects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=153,
)


_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='facial_emotions.Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='facial_emotions.Rect.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='facial_emotions.Rect.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='facial_emotions.Rect.w', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='facial_emotions.Rect.h', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=205,
)


_RET = _descriptor.Descriptor(
  name='ret',
  full_name='facial_emotions.ret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='facial_emotions.ret.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=227,
)


_FACE_EMOTION = _descriptor.Descriptor(
  name='face_emotion',
  full_name='facial_emotions.face_emotion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emotion_labels', full_name='facial_emotions.face_emotion.emotion_labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=300,
)


_EMOTION = _descriptor.Descriptor(
  name='Emotion',
  full_name='facial_emotions.Emotion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emotion', full_name='facial_emotions.Emotion.emotion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=328,
)


_EMOTION_LABELS = _descriptor.Descriptor(
  name='Emotion_labels',
  full_name='facial_emotions.Emotion_labels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angry', full_name='facial_emotions.Emotion_labels.angry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disgust', full_name='facial_emotions.Emotion_labels.disgust', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fear', full_name='facial_emotions.Emotion_labels.fear', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happy', full_name='facial_emotions.Emotion_labels.happy', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sad', full_name='facial_emotions.Emotion_labels.sad', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surprise', full_name='facial_emotions.Emotion_labels.surprise', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neutral', full_name='facial_emotions.Emotion_labels.neutral', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=455,
)


_EMOREQUEST = _descriptor.Descriptor(
  name='emoRequest',
  full_name='facial_emotions.emoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emolabel', full_name='facial_emotions.emoRequest.emolabel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=487,
)


_EMOREPLY = _descriptor.Descriptor(
  name='emoReply',
  full_name='facial_emotions.emoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emotion', full_name='facial_emotions.emoReply.emotion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_faces', full_name='facial_emotions.emoReply.number_of_faces', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=541,
)

_RECTS.fields_by_name['rects'].message_type = _RECT
_FACE_EMOTION.fields_by_name['emotion_labels'].message_type = _EMOTION_LABELS
DESCRIPTOR.message_types_by_name['image_frame'] = _IMAGE_FRAME
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Rects'] = _RECTS
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
DESCRIPTOR.message_types_by_name['ret'] = _RET
DESCRIPTOR.message_types_by_name['face_emotion'] = _FACE_EMOTION
DESCRIPTOR.message_types_by_name['Emotion'] = _EMOTION
DESCRIPTOR.message_types_by_name['Emotion_labels'] = _EMOTION_LABELS
DESCRIPTOR.message_types_by_name['emoRequest'] = _EMOREQUEST
DESCRIPTOR.message_types_by_name['emoReply'] = _EMOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image_frame = _reflection.GeneratedProtocolMessageType('image_frame', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE_FRAME,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.image_frame)
  ))
_sym_db.RegisterMessage(image_frame)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.Point)
  ))
_sym_db.RegisterMessage(Point)

Rects = _reflection.GeneratedProtocolMessageType('Rects', (_message.Message,), dict(
  DESCRIPTOR = _RECTS,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.Rects)
  ))
_sym_db.RegisterMessage(Rects)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), dict(
  DESCRIPTOR = _RECT,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.Rect)
  ))
_sym_db.RegisterMessage(Rect)

ret = _reflection.GeneratedProtocolMessageType('ret', (_message.Message,), dict(
  DESCRIPTOR = _RET,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.ret)
  ))
_sym_db.RegisterMessage(ret)

face_emotion = _reflection.GeneratedProtocolMessageType('face_emotion', (_message.Message,), dict(
  DESCRIPTOR = _FACE_EMOTION,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.face_emotion)
  ))
_sym_db.RegisterMessage(face_emotion)

Emotion = _reflection.GeneratedProtocolMessageType('Emotion', (_message.Message,), dict(
  DESCRIPTOR = _EMOTION,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.Emotion)
  ))
_sym_db.RegisterMessage(Emotion)

Emotion_labels = _reflection.GeneratedProtocolMessageType('Emotion_labels', (_message.Message,), dict(
  DESCRIPTOR = _EMOTION_LABELS,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.Emotion_labels)
  ))
_sym_db.RegisterMessage(Emotion_labels)

emoRequest = _reflection.GeneratedProtocolMessageType('emoRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMOREQUEST,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.emoRequest)
  ))
_sym_db.RegisterMessage(emoRequest)

emoReply = _reflection.GeneratedProtocolMessageType('emoReply', (_message.Message,), dict(
  DESCRIPTOR = _EMOREPLY,
  __module__ = 'facial_emotions_pb2'
  # @@protoc_insertion_point(class_scope:facial_emotions.emoReply)
  ))
_sym_db.RegisterMessage(emoReply)



_EMOTION_RECOGNIZER = _descriptor.ServiceDescriptor(
  name='Emotion_recognizer',
  full_name='facial_emotions.Emotion_recognizer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=544,
  serialized_end=813,
  methods=[
  _descriptor.MethodDescriptor(
    name='image_processor',
    full_name='facial_emotions.Emotion_recognizer.image_processor',
    index=0,
    containing_service=None,
    input_type=_IMAGE_FRAME,
    output_type=_RECTS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='emotion_classifier',
    full_name='facial_emotions.Emotion_recognizer.emotion_classifier',
    index=1,
    containing_service=None,
    input_type=_FACE_EMOTION,
    output_type=_EMOTION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamStreamEmotion',
    full_name='facial_emotions.Emotion_recognizer.StreamStreamEmotion',
    index=2,
    containing_service=None,
    input_type=_EMOREQUEST,
    output_type=_EMOREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMOTION_RECOGNIZER)

DESCRIPTOR.services_by_name['Emotion_recognizer'] = _EMOTION_RECOGNIZER

# @@protoc_insertion_point(module_scope)
